"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SubscriptionRequestBuilderNavigationMetadata = exports.SubscriptionRequestBuilderUriTemplate = void 0;
/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
var index_js_1 = require("./calendar/index.js");
// @ts-ignore
var index_js_2 = require("./feed/index.js");
/**
 * The calendar property
 */
get;
calendar();
CalendarRequestBuilder;
/**
 * The feed property
 */
get;
feed();
FeedRequestBuilder;
/**
 * Uri template for the request builder.
 */
exports.SubscriptionRequestBuilderUriTemplate = "{+baseurl}/subscription";
/**
 * Metadata for all the navigation properties in the request builder.
 */
exports.SubscriptionRequestBuilderNavigationMetadata = {
    calendar: {
        requestsMetadata: index_js_1.CalendarRequestBuilderRequestsMetadata,
    },
    feed: {
        requestsMetadata: index_js_2.FeedRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
//# sourceMappingURL=index.js.map