/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { EventRequestBuilderNavigationMetadata, EventRequestBuilderRequestsMetadata, type EventRequestBuilder } from './event';
// @ts-ignore
import { SubscriptionRequestBuilderNavigationMetadata, type SubscriptionRequestBuilder } from './subscription';
// @ts-ignore
import { apiClientProxifier, registerDefaultDeserializer, registerDefaultSerializer, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type RequestAdapter } from '@microsoft/kiota-abstractions';
// @ts-ignore
import { FormParseNodeFactory, FormSerializationWriterFactory } from '@microsoft/kiota-serialization-form';
// @ts-ignore
import { JsonParseNodeFactory, JsonSerializationWriterFactory } from '@microsoft/kiota-serialization-json';
// @ts-ignore
import { MultipartSerializationWriterFactory } from '@microsoft/kiota-serialization-multipart';
// @ts-ignore
import { TextParseNodeFactory, TextSerializationWriterFactory } from '@microsoft/kiota-serialization-text';

/**
 * Instantiates a new {@link FalahClient} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-ignore
export function createFalahClient(requestAdapter: RequestAdapter) {
    registerDefaultSerializer(JsonSerializationWriterFactory);
    registerDefaultSerializer(TextSerializationWriterFactory);
    registerDefaultSerializer(FormSerializationWriterFactory);
    registerDefaultSerializer(MultipartSerializationWriterFactory);
    registerDefaultDeserializer(JsonParseNodeFactory);
    registerDefaultDeserializer(TextParseNodeFactory);
    registerDefaultDeserializer(FormParseNodeFactory);
    const pathParameters: Record<string, unknown> = {
        "baseurl": requestAdapter.baseUrl,
    };
    return apiClientProxifier<FalahClient>(requestAdapter, pathParameters, FalahClientNavigationMetadata, undefined);
}
/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface FalahClient extends BaseRequestBuilder<FalahClient> {
    /**
     * The event property
     */
    get event(): EventRequestBuilder;
    /**
     * The subscription property
     */
    get subscription(): SubscriptionRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const FalahClientUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const FalahClientNavigationMetadata: Record<Exclude<keyof FalahClient, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    event: {
        requestsMetadata: EventRequestBuilderRequestsMetadata,
        navigationMetadata: EventRequestBuilderNavigationMetadata,
    },
    subscription: {
        navigationMetadata: SubscriptionRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
