/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CalendarRequestBuilderRequestsMetadata, type CalendarRequestBuilder } from './calendar/index.js';
// @ts-ignore
import { FeedRequestBuilderRequestsMetadata, type FeedRequestBuilder } from './feed/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /subscription
 */
export interface SubscriptionRequestBuilder extends BaseRequestBuilder<SubscriptionRequestBuilder> {
    /**
     * The calendar property
     */
    get calendar(): CalendarRequestBuilder;
    /**
     * The feed property
     */
    get feed(): FeedRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const SubscriptionRequestBuilderUriTemplate = "{+baseurl}/subscription";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SubscriptionRequestBuilderNavigationMetadata: Record<Exclude<keyof SubscriptionRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    calendar: {
        requestsMetadata: CalendarRequestBuilderRequestsMetadata,
    },
    feed: {
        requestsMetadata: FeedRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
