"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EventRequestBuilderRequestsMetadata = exports.EventRequestBuilderNavigationMetadata = exports.EventRequestBuilderUriTemplate = void 0;
/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
var index_js_1 = require("../models/index.js");
// @ts-ignore
var index_js_2 = require("./item/index.js");
/**
 * Uri template for the request builder.
 */
exports.EventRequestBuilderUriTemplate = "{+baseurl}/event";
/**
 * Metadata for all the navigation properties in the request builder.
 */
exports.EventRequestBuilderNavigationMetadata = {
    byId: {
        requestsMetadata: index_js_2.EventItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
exports.EventRequestBuilderRequestsMetadata = {
    get: {
        uriTemplate: exports.EventRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory: "ArrayBuffer",
    },
    post: {
        uriTemplate: exports.EventRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory: "ArrayBuffer",
        requestBodyContentType: "application/json",
        requestBodySerializer: index_js_1.serializeEvent,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
//# sourceMappingURL=index.js.map