"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FalahClientNavigationMetadata = exports.FalahClientUriTemplate = exports.createFalahClient = void 0;
/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
var index_js_1 = require("./event/index.js");
// @ts-ignore
var index_js_2 = require("./subscription/index.js");
// @ts-ignore
var kiota_abstractions_1 = require("@microsoft/kiota-abstractions");
// @ts-ignore
var kiota_serialization_form_1 = require("@microsoft/kiota-serialization-form");
// @ts-ignore
var kiota_serialization_json_1 = require("@microsoft/kiota-serialization-json");
// @ts-ignore
var kiota_serialization_multipart_1 = require("@microsoft/kiota-serialization-multipart");
// @ts-ignore
var kiota_serialization_text_1 = require("@microsoft/kiota-serialization-text");
/**
 * Instantiates a new {@link FalahClient} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-ignore
function createFalahClient(requestAdapter) {
    kiota_abstractions_1.registerDefaultSerializer(kiota_serialization_json_1.JsonSerializationWriterFactory);
    kiota_abstractions_1.registerDefaultSerializer(kiota_serialization_text_1.TextSerializationWriterFactory);
    kiota_abstractions_1.registerDefaultSerializer(kiota_serialization_form_1.FormSerializationWriterFactory);
    kiota_abstractions_1.registerDefaultSerializer(kiota_serialization_multipart_1.MultipartSerializationWriterFactory);
    kiota_abstractions_1.registerDefaultDeserializer(kiota_serialization_json_1.JsonParseNodeFactory);
    kiota_abstractions_1.registerDefaultDeserializer(kiota_serialization_text_1.TextParseNodeFactory);
    kiota_abstractions_1.registerDefaultDeserializer(kiota_serialization_form_1.FormParseNodeFactory);
    if (requestAdapter.baseUrl === undefined || requestAdapter.baseUrl === null || requestAdapter.baseUrl === "") {
        requestAdapter.baseUrl = "http://127.0.0.1:5800";
    }
    var pathParameters = {
        "baseurl": requestAdapter.baseUrl,
    };
    return kiota_abstractions_1.apiClientProxifier(requestAdapter, pathParameters, exports.FalahClientNavigationMetadata, undefined);
}
exports.createFalahClient = createFalahClient;
/**
 * The event property
 */
get;
event();
EventRequestBuilder;
/**
 * The subscription property
 */
get;
subscription();
SubscriptionRequestBuilder;
/**
 * Uri template for the request builder.
 */
exports.FalahClientUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
exports.FalahClientNavigationMetadata = {
    event: {
        requestsMetadata: index_js_1.EventRequestBuilderRequestsMetadata,
        navigationMetadata: index_js_1.EventRequestBuilderNavigationMetadata,
    },
    subscription: {
        navigationMetadata: index_js_2.SubscriptionRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
//# sourceMappingURL=falahClient.js.map